const assert=require("node:assert/strict");
const {toV3Payload,publicV3Receipt}=require("./build/jct-v3-contract.js");
const {fromLanding}=require("./build/jct-first-touch.js");
const {safeStatus}=require("./build/jct-my-tow-guard.js");
const a=fromLanding("https://test.example/contact?utm_source=search&phone=SHOULD_NOT_SAVE","https://ref.example/r?private=VALUE",390);
assert.equal(a.utm_source,"search");
assert.equal(a.referrer,"https://ref.example/r");
assert.equal(a.device_type,"mobile");
assert.ok(!JSON.stringify(a).includes("SHOULD_NOT_SAVE"));
const p=toV3Payload({name:" Jane ",phone:"1234567890",pickup:" Main street ",consent:true},a);
assert.equal(p.name,"Jane");
assert.equal(p.pickup,"Main street");
assert.equal(p.is_demo,false);
assert.equal(p.utm_source,"search");
const receipt=publicV3Receipt({lead_number:81,lead_id:"internal-only",upload_prefix:"private"});
assert.deepEqual(receipt,{reference:81});
assert.ok(!JSON.stringify(receipt).includes("lead_id"));
assert.ok(!JSON.stringify(receipt).includes("upload_prefix"));
assert.throws(()=>publicV3Receipt({lead_id:"x"}));
assert.throws(()=>publicV3Receipt({lead_number:0}));
assert.deepEqual(safeStatus({status:"EN_ROUTE",phone:"private"}),{status:"En route"});
assert.equal(safeStatus({status:"INTERNAL_ONLY"}),null);
assert.equal(safeStatus({ok:false,status:"DISPATCHED"}),null);
console.log("PASS staged offline contract checks (no network/no CRM writes).");
